FROM golang:1.5.1

RUN mkdir -p /go/src/github.com/namely/arnoldb
WORKDIR /go/src/github.com/namely/arnoldb

RUN go get github.com/tools/godep
RUN go get -u github.com/golang/protobuf/proto
RUN go get -u github.com/golang/protobuf/protoc-gen-go
RUN go get google.golang.org/grpc

COPY Godeps /go/src/github.com/namely/arnoldb/Godeps
RUN /go/bin/godep restore
