db_arnoldb:
  image: postgres:9.4
  environment:
    POSTGRES_DB: arnold

arnoldb:
  image: registry.namely.tech/namely/arnoldb:afe92fa4
  ports:
    - "8080"
  environment:
    PG_USER: postgres
    PG_HOST: db_arnoldb
    PG_DBNAME: arnold
    STORAGE_ENGINE: postgres
  links:
    - db_arnoldb

dashboard:
  build: .
  dockerfile: Dockerfile-dev
  command: go run app.go
  volumes: .:/dashboard
  ports:
    - "3000:3000"
  environment:
    ARNOLDB_ADDR: arnoldb
    ARNOLDB_PORT: 8080
